// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: GPL-2.0-only

extern crate self as chrony_candm; //We need this so that the fully qualified identifiers generated by macros can resolve

#[cfg(feature = "with_tokio")]
mod async_net;
pub mod common;
mod net;
pub mod reply;
pub mod request;

#[cfg(feature = "with_tokio")]
pub use async_net::*;
pub use net::*;
